CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL,
  "roleId" varchar NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "videocourses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "pivote_courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryId" int NOT NULL,
  "courseId" int NOT NULL
);

CREATE TABLE "pivote_users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int NOT NULL,
  "courseId" int NOT NULL
);

CREATE TABLE "pivote_users_videocourses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int NOT NULL,
  "videocourseId" int NOT NULL
);

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("courseId") REFERENCES "courses" ("id");

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("categoryId") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("roleId") REFERENCES "roles" ("id");

ALTER TABLE "pivote_users_courses" ADD FOREIGN KEY ("id") REFERENCES "users" ("id");

ALTER TABLE "pivote_users_courses" ADD FOREIGN KEY ("courseId") REFERENCES "courses" ("id");

ALTER TABLE "pivote_users_videocourses" ADD FOREIGN KEY ("videocourseId") REFERENCES "videocourses" ("id");

ALTER TABLE "pivote_users_videocourses" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
